slibrary <- function(fun){
  fun_name <- as.character(substitute(fun))
  if(is.element(fun_name, installed.packages()[,1]) == FALSE)
    install.packages(fun_name)
  COMMAND <- paste("library(", fun_name, ")", sep = "")
  eval(parse(text = COMMAND))
}

# dependences 
slibrary(shiny)
slibrary(leaflet)
slibrary(raster)
slibrary(rgdal)
slibrary(leaflet)
slibrary(RColorBrewer)
slibrary(reshape2)
slibrary(plotly)
slibrary(gapminder)
slibrary(ggplot2)
slibrary(rsconnect)
slibrary(shinyFiles)
slibrary(shinyWidgets)
slibrary(exactextractr)
slibrary(data.table)
slibrary(sf)
slibrary(ncdf4)
slibrary(stringr)